name: flutter_test_practice_1
description: 練習各種測試

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # BSD
  # Android, IOS, Linux, macOS, WEB, Windows
  cupertino_icons: ^1.0.3

  # MIT
  # Android, IOS, Linux, macOS, WEB, Windows
  provider: ^6.0.0
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test:
  test_core:

flutter:
  uses-material-design: true

  assets:
    - assets/